sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=sabinca97/dockerslika
  - IMAGE_TAG=0.0.1-SNAPSHOT-$TRAVIS_JOB_NUMBER
script:
- docker build -t "$DOCKER_IMAGE":"$IMAGE_TAG" -t "$DOCKER_IMAGE":latest .
- docker tag "$DOCKER_IMAGE":"$IMAGE_TAG" $DOCKER_USERNAME/"$DOCKER_IMAGE":"$IMAGE_TAG"
- docker tag "$DOCKER_IMAGE":"$IMAGE_TAG" $DOCKER_USERNAME/"$DOCKER_IMAGE":latest
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_USERNAME"/"$DOCKER_IMAGE":"$IMAGE_TAG"
- docker push "$DOCKER_USERNAME"/"$DOCKER_IMAGE":latest