apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-catalog
  template:
    metadata:
      labels:
        app: image-catalog
    spec:
      containers:
      - image: sabinca97/novaslika:2
        name: image-catalog
        env:
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://ec2-52-1-95-247.compute-1.amazonaws.com:5432/d8gnrm64ecchtp
        - name: KUMULUZEE_DATASOURCES0_USERNAME
          value: vdjkikowgtbsmb
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          value: 90c2a354319c666def2d0e862c1d558df0a4919d7d4fd4753e95642899343dbc
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: image-catalog
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: server
  selector:
    app: image-catalog


#    kubectl create -f image-catalog-deployment.yaml
#  kubectl get services
#  kubectl get deployments