kumuluzee:
  name: image-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/vdjkikowgtbsmb
      connection-url: jdbc:postgresql://ec2-52-1-95-247.compute-1.amazonaws.com/d8gnrm64ecchtp
      username: vdjkikowgtbsmb
      password: 90c2a354319c666def2d0e862c1d558df0a4919d7d4fd4753e95642899343dbc
      listen_addresses: "*"
      pool:
        max-size: 5
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/vdjkikowgtbsmb
    metrics:
      web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /metrics/*
        status-codes: "200, 500"
      - name: images-endpoint
        url-pattern: /v1/images/*
      servlet:
        enabled: true
        mapping: /my-metrics-servlet

rest-properties:
  maintenance-mode: false
  broken: false